### PR TITLE
Support custom envrionment variables

### LINKED ISSUE #11: Set EnvironmentVariables from options
I would like to set some environment variables from the host ASP.NET application. I found out that JavaScriptService supports is: https://github.com/aspnet/JavaScriptServices/blob/fb19ee8923b5ef7ebb125bc6e5a1a182cfadfe88/src/Microsoft.AspNetCore.NodeServices/Configuration/NodeServicesOptions.cs#L90

Do you accept a PR that allows to set additional environment variable from NodeRenderEngineOptions?

Great project btw!

### PR DESCRIPTION
**Pull request by tim-cools**
closes #11

### CODE REVIEW

**Comment by tim-cools** [comment]
@pauldotknopf Any idea if and when you can take this in and update the nuget? Is it days / weeks or longer ? Just so I know whether I have to create temp custom build, or I can wait... Thx!!

**Comment by pauldotknopf** [comment]
Sorry for the delay. I am working on a new build now.

**Comment by pauldotknopf** [comment]
1.4 has your changes in it.

**Comment by tim-cools** [comment]
@pauldotknopf ok, thanks!

**Pull request merged**
